# Generated by Django 4.1.1 on 2022-10-20 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_trilha', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('localizacao', models.TextField()),
                ('duracao', models.IntegerField()),
                ('nivel', models.CharField(max_length=20)),
                ('curiosidades', models.CharField(blank=True, max_length=400, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
